<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="LogicBuilder.Expressions.Utils" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contoso.Common.Configuration\Contoso.Common.Configuration.csproj" />
    <ProjectReference Include="..\Contoso.Parameters\Contoso.Parameters.csproj" />
  </ItemGroup>

</Project>
