<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enrollment.AutoMapperProfiles\Enrollment.AutoMapperProfiles.csproj" />
    <ProjectReference Include="..\Enrollment.BSL.AutoMapperProfiles\Enrollment.BSL.AutoMapperProfiles.csproj" />
    <ProjectReference Include="..\Enrollment.Contexts\Enrollment.Contexts.csproj" />
    <ProjectReference Include="..\Enrollment.Repositories\Enrollment.Repositories.csproj" />
    <ProjectReference Include="..\Enrollment.Stores\Enrollment.Stores.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DropDowns.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
