<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LogicBuilder.EntityFrameworkCore.SqlServer" Version="7.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Contoso.Contexts\Contoso.Contexts.csproj" />
  </ItemGroup>

</Project>
