using Contoso.Parameters.Expressions;

namespace Contoso.XPlatform.Flow
{
    public class DummyOperatorParameterConstructor
    {
        public DummyOperatorParameterConstructor
        (
            AddBinaryOperatorParameters addBinaryOperatorParameter,
            AllOperatorParameters allOperatorParameter,
            AndBinaryOperatorParameters andBinaryOperatorParameter,
            AnyOperatorParameters anyOperatorParameter,
            AsEnumerableOperatorParameters asEnumerableOperatorParameters,
            AsQueryableOperatorParameters asQueryableOperatorParameter,
            AverageOperatorParameters averageOperatorParameter,
            BinaryOperatorParameters binaryOperatorParameter,
            CastOperatorParameters castOperatorParameter,
            CeilingOperatorParameters ceilingOperatorParameter,
            CollectionCastOperatorParameters collectionCastOperatorParameter,
            CollectionConstantOperatorParameters collectionConstantOperatorParameter,
            ConcatOperatorParameters concatOperatorParameter,
            ConstantOperatorParameters constantOperatorParameter,
            ContainsOperatorParameters containsOperatorParameter,
            ConvertCharArrayToStringOperatorParameters convertCharArrayToStringOperatorParameter,
            ConvertOperatorParameters convertOperatorParameter,
            ConvertToEnumOperatorParameters convertToEnumOperatorParameter,
            ConvertToNullableUnderlyingValueOperatorParameters convertToNullableUnderlyingValueOperatorParameter,
            ConvertToNumericDateOperatorParameters convertToNumericDateOperatorParameter,
            ConvertToNumericTimeOperatorParameters convertToNumericTimeOperatorParameter,
            ConvertToStringOperatorParameters convertToStringOperatorParameter,
            CountOperatorParameters countOperatorParameter,
            CustomMethodOperatorParameters customMethodOperatorParameter,
            DateOperatorParameters dateOperatorParameter,
            DayOperatorParameters dayOperatorParameter,
            DistinctOperatorParameters distinctOperatorParameter,
            DivideBinaryOperatorParameters divideBinaryOperatorParameter,
            EndsWithOperatorParameters endsWithOperatorParameter,
            EqualsBinaryOperatorParameters equalsBinaryOperatorParameter,
            FilterLambdaOperatorParameters filterLambdaOperatorParameter,
            FirstOperatorParameters firstOperatorParameter,
            FirstOrDefaultOperatorParameters firstOrDefaultOperatorParameter,
            FloorOperatorParameters floorOperatorParameter,
            FractionalSecondsOperatorParameters fractionalSecondsOperatorParameter,
            GreaterThanBinaryOperatorParameters greaterThanBinaryOperatorParameter,
            GreaterThanOrEqualsBinaryOperatorParameters greaterThanOrEqualsBinaryOperatorParameter,
            GroupByOperatorParameters groupByOperatorParameter,
            HasOperatorParameters hasOperatorParameter,
            HourOperatorParameters hourOperatorParameter,
            IEnumerableSelectorLambdaOperatorParameters enumerableSelectorLambdaOperatorParameter,
            InOperatorParameters inOperatorParameter,
            IndexOfOperatorParameters indexOfOperatorParameter,
            IsOfOperatorParameters isOfOperatorParameter,
            LastOperatorParameters lastOperatorParameter,
            LastOrDefaultOperatorParameters lastOrDefaultOperatorParameter,
            LengthOperatorParameters lengthOperatorParameter,
            LessThanBinaryOperatorParameters lessThanBinaryOperatorParameter,
            LessThanOrEqualsBinaryOperatorParameters lessThanOrEqualsBinaryOperatorParameter,
            MaxDateTimeOperatorParameters maxDateTimeOperatorParameter,
            MaxOperatorParameters maxOperatorParameter,
            MemberInitOperatorParameters memberInitOperatorParameter,
            MemberSelectorOperatorParameters memberSelectorOperatorParameter,
            MinDateTimeOperatorParameters minDateTimeOperatorParameter,
            MinOperatorParameters minOperatorParameter,
            MinuteOperatorParameters minuteOperatorParameter,
            ModuloBinaryOperatorParameters moduloBinaryOperatorParameter,
            MonthOperatorParameters monthOperatorParameter,
            MultiplyBinaryOperatorParameters multiplyBinaryOperatorParameter,
            NegateOperatorParameters negateOperatorParameter,
            NotOperatorParameters notOperatorParameter,
            NotEqualsBinaryOperatorParameters notEqualsBinaryOperatorParameter,
            NowDateTimeOperatorParameters nowDateTimeOperatorParameter,
            OrBinaryOperatorParameters orBinaryOperatorParameter,
            OrderByOperatorParameters orderByOperatorParameter,
            ParameterOperatorParameters parameterOperatorParameter,
            RoundOperatorParameters roundOperatorParameter,
            SecondOperatorParameters secondOperatorParameter,
            SelectOperatorParameters selectOperatorParameter,
            SelectManyOperatorParameters selectManyOperatorParameter,
            SelectorLambdaOperatorParameters selectorLambdaOperatorParameter,
            SingleOperatorParameters singleOperatorParameter,
            SingleOrDefaultOperatorParameters singleOrDefaultOperatorParameter,
            SkipOperatorParameters skipOperatorParameter,
            StartsWithOperatorParameters startsWithOperatorParameter,
            SubstringOperatorParameters substringOperatorParameter,
            SubtractBinaryOperatorParameters subtractBinaryOperatorParameter,
            SumOperatorParameters sumOperatorParameter,
            TakeOperatorParameters takeOperatorParameter,
            ThenByOperatorParameters thenByOperatorParameter,
            TimeOperatorParameters timeOperatorParameter,
            ToListOperatorParameters toListOperatorParameter,
            ToLowerOperatorParameters toLowerOperatorParameter,
            TotalOffsetMinutesOperatorParameters totalOffsetMinutesOperatorParameter,
            TotalSecondsOperatorParameters totalSecondsOperatorParameter,
            ToUpperOperatorParameters toUpperOperatorParameter,
            TrimOperatorParameters trimOperatorParameter,
            WhereOperatorParameters whereOperatorParameter,
            YearOperatorParameters yearOperatorParameter
        )
        {

        }
    }
}
