<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="LogicBuilder.Expressions.Utils" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enrollment.Common.Configuration\Enrollment.Common.Configuration.csproj" />
    <ProjectReference Include="..\Enrollment.Parameters\Enrollment.Parameters.csproj" />
  </ItemGroup>

</Project>
